version: '3.8'

services:
  hextag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hextag-web
    restart: unless-stopped
    ports:
      # Format: "HOST_PORT:CONTAINER_PORT"
      - "${HEXTAG_PORT:-8480}:80"
    environment:
      - NODE_ENV=production
